#!/bin/bash
clear
RED='\033[0;31m'
NC='\033[0m'
BLUE="\033[36m"
GREEN='\033[0;32m'
grenbo="\e[92;1m"
UUID=$(tr </dev/urandom -dc a-z | head -c8)
echo -e "   ┌──────────────────────────────────────────┐\033[0m"
echo -e "   │\033[0m\033[101m        BOT  AUTOSCRIPT  TELEGRAM         \033[0m|\033[0m"
echo -e "   └──────────────────────────────────────────┘\033[0m"
echo -e "            Telegram Bot Setup menu"
echo -e "          make vpn in the telegram bot"
echo -e "──────────────────────────────────────────────────"
echo -e "   ${BLUE}get this value from @BotFather, required${NC}"
echo -e "    ${BLUE}take your id at @MissRose_bot,cmd (/id)${NC}"
echo -e "  ${BLUE}Tutorial? Join in the @SillaVpnGr group${NC}"
echo -e "       ==>> CTRL + C GO TO BACK <<=="
echo -e ""
echo -e "            CONTOH : t.me/SilaaVPN"
echo -e "         CONTOH : wa.me/62812xxxx67373"
echo -e "           ────────────────────────"
read -e -p "Input your Bot Token : " TOKET
read -e -p "Input your Id Telegram : " IDTELE
read -e -p "Input your Whstapp : " WHSTAP
read -e -p "Input your Telegram : " TELE


update_python() {
    echo "update repository python"
    apt install python3 python3-pip -y
    wget https://github.com/SETANTAZVPN/permission/raw/main/regis.zip
    unzip regis.zip
}

main() {
    update_python
    cd /root/regis/shell
    chmod +x *
    cp * /usr/bin
    pip3 install -r /root/regis/requirements.txt
    cd 
    cat >/usr/bin/jhhhhh <<EOF
#!/bin/bash

cd 
python3.8 -m regis
EOF
    chmod +x /usr/bin/jhhhhh
    cat >/etc/systemd/system/regis.service <<EOF
[Unit]
Description=backend
After=network.target

[Service]
WorkingDirectory=/root/
ExecStart=python3 -m regis
Restart=always

[Install]
WantedBy=multi-user.target
EOF
    cat >id <<EOF
TELEGRAM="$TELE" #CONTOH t.me/rullpqh
WHATSAPP="$WHSTAP"  #CONTOH wa.me/6281584099035
EOF
    cat >regis/var.txt <<EOF
BOT_TOKEN="$TOKET"
ADMIN="$IDTELE"
SESSIONS="${UUID}"
EOF
    systemctl daemon-reload
    systemctl stop regis
    systemctl enable regis
    systemctl start regis
    systemctl restart regis
    clear
#    systemctl status regggg
}
main "$@"
echo " Bot Sukses di Install.."